### PR TITLE
みんなの世界

### PR DESCRIPTION
**Pull request by Ristellise**
...

### CODE REVIEW

**Comment by TheOneric** [comment]
A bit besides the topic (sorry for that), but since you started to reädd (some?) v4++ functionality to Aegisub, does that mean you have any actual v4++ releases? If you do, I'd be very interested in taking a look at them and knowing where and when they came from.

*(More on-topic:  `v4++` also includes a new `[V4++ Styles]` section name and requires changes to Dialogue and Style parsing, but I guess that's why this is a WIP PR.)*

**Comment by Ristellise** [comment]
> A bit besides the topic (sorry for that), but since you started to reädd (some?) v4++ functionality to Aegisub, does that mean you have any actual v4++ releases? If you do, I'd be very interested in taking a look at them and knowing where and when they came from.
> 
> _(More on-topic: `v4++` also includes a new `[V4++ Styles]` section name and requires changes to Dialogue and Style parsing, but I guess that's why this is a WIP PR.)_

Hi! I actually don't have any V4++ releases. So anything now is setting ground work in preparation for v4++.

**Comment by Ristellise** [comment]
I'm going to push a commit which adds untested support for margins.

The behavior flow should look like this:

- If the script read is + version & Aegisub is ++ version:
  - copy top margin to bottom margin, enable top margin
- If script read is ++ version, Aegisub is in ++ version:
  - Use Bottom margin and top margin like usual.
- If script read is ++ version, & Aegisub is in + version:
  - Margins are merged and top margins are disabled. When saving only the bottom (Vertical) margins are saved.
- If script read is + version, & Aegisub is in + version:
  - Use Vertical margin. Copy vertical margin to bottom margin for compat with lua scripts.

Please let me know if something breaks or like weird behaviour.
FYI I haven't updated libass version yet. So no ABI changes for now...

**Comment by Ristellise** [comment]
Essentially abandoned. if anyone wants to pick up the mantle, feel free.

**Pull request closed without merging**
